id: P4F1B5901
initial_creation_type: input
source_metadata:
  Title: Sphuṭārthā Abhidharmakośa Vyākhyā (Vol 1)
  Editor: Narendra Nath Law
  Publisher: Luzac & Co.
  Place of Publication: London, England
  Year: '1949'
  स्फ़ुटार्थाभिधर्मकोशव्याख्यायाम् (vol 1):
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:23:31.628478'
last_modified_at: '2022-03-08T17:23:31.628485'
